Proposer listes consulaires pour les Francais de l'etranger
jlm2017/procurations pull request #2
Opened 2017-03-24 07:15 UTC by picsoung

Suite à la conversion sur #1 

J'ai tenté un premier truc pour afficher les listes consulaires.

Les données viennent d'ici: https://www.legifrance.gouv.fr/eli/arrete/2017/3/14/MAEF1707930A/jo#JORFSCTA000034258461

Il y a peut être quelques edge-case lié à ca https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000033734794

J'ai pas trouvé d'API, du coup j'ai fait un JSON du tableau, et un petit endpoint qui filtre, pour faire le même mecanisme que l'API du ban.

Ce qu'il reste à faire:

- un button radio ou équivalent pour choisir entre France ou Étranger
- sauver dans redis
- traitement du form une fois validé.

2017-03-24 07:22 UTC, picsoung commented
Visuellement ca donne ca:
<img width="804" alt="votez_pour_jean-luc_melenchon_par_procuration" src="https://cloud.githubusercontent.com/assets/172072/24284314/ef782f66-1027-11e7-8115-4e7a32dda0ea.png">

2017-03-24 11:52 UTC, jillro requested changes
Merci beaucoup pour ta contribution ! Ça répond au besoin et si tu veux bien continuer à travailler dessus, on peut la merger rapidement.

Le problème de départ est qu'on ne peut pas utiliser le même mécanisme de matching qu'avec la France, car les FE sont très mal référencés.

On va donc créer une boite mail recensant les demandes et les redirigeant vers les groupes d'appui. Le rôle de l'interface sur procurations.jlm2017.fr sera simplement de générer un mail automatique vers cette adresse.

Par ailleurs, il vaut garder l'interface pour la majorité des utilisateurs (non FE) aussi simple qu'elle l'est actuellement. Donc pas de bouton radio (un clic supplémentaire pour la majorité des gens), mais un lien "Je suis inscrit.e sur une liste consulaire" qui renvoie vers une autre page et un autre formulaire :)

Si t'as le temps d'avancer là dessus, merci beaucoup !

2017-03-24 11:52 UTC, guilro commented on package.json
> +    "underscore": "^1.8.3",
Merci de ne pas rajouter de dépendances qui ne sont pas utilisées dans le projet :)

2017-03-24 11:52 UTC, guilro commented on public/main.js
> +    load: function(query, callback) {
Étant donné que le fichier JSON fait 80ko, je pense qu'on peut l'envoyer et gérer tout cela côté client.

2017-03-25 20:54 UTC, picsoung commented
Merci @guilro pour les commentaires :)

J'ai modifié pour avoir une page à part pour éviter la confusion.

Je voulais juste m'accorder avec toi sur comment on enregistre l'information dans la base.
Dans le même champs `commune` ou quelque chose à part?

Il y'a aussi des choses à changer dans la partie admin? Tu as des pistes?

En fonction je fais les changements, et je propose un flot complet :)

2017-03-26 03:00 UTC, AtishaGarinMchd commented
La premiere page indique 'Commune', il y a t-il possibilité de modifier le texte pour indiquer la prise en charge des FE ? La réception d'email étant engageante, le doute pourrait dissuader un FE.

Propositions:
Premiere phrase: remplacer 'commune' par 'lieu'
Bouton: remplacer par 'RECHERCHER'

2017-03-27 08:49 UTC, guilro commented on routes/liste-consulaire.js
> +
à rajouter ici (je le ferai) le code d'envoi du mail

2017-03-27 08:49 UTC, guilro commented on routes/requests.js
> +  console.log("BODY",req.body);
supprimer

2017-03-27 08:49 UTC, guilro commented on routes/requests.js
> +  console.log("TOKEN",token)
supprimer

2017-03-27 08:49 UTC, guilro commented on views/step2-liste-consulaire.pug
> +    Merci&nbsp! Votre adresse email #{email} est bien confirmée.
typo

2017-03-27 08:50 UTC, guilro commented on views/step2-liste-consulaire.pug
> +      Dernière étape&nbsp;: choisissez ci-dessous votre commune, nous essaierons
adapter le texte :)

2017-03-27 08:50 UTC, guilro commented
Salut :) Il n'y a rien a enregistrer dans la base. Il y a suffisamment peu de personnes concernées pour que cela soit plus rapide de les traiter manuellement.

Pour l'instant la PR n'est pas assez propre pour être mergée, j'ai fait plusieurs commentaires :)

2017-03-28 02:45 UTC, picsoung commented
Top!
Merci @guilro pour les commentaires, j'ai viré les console.log disgracieux.
Ca devrait être bon alors. Je te laisse voir comment se passe le traitement derrière.

Avec le décalage horaire on se loupe, mais je peux être plus réactif demain pour pusher ça rapidement.

2017-03-28 09:40 UTC, guilro commented on views/step2-liste-consulaire.pug
> +  else
ce paragraphe est inutile il me semble ? on sait déjà qu'on est sur une liste consulaire

2017-03-28 15:46 UTC, guilro commented
Je suis parti de ton travail pour terminé un commit :) Ce sera traité manuellement, mais on peut désormais choisir son consulat lorsque l'on est sur un LEC !

2017-03-28 15:46 UTC, closed without merging

2017-03-28 17:51 UTC, picsoung commented
top ! merci pour les changements :)
Je vais communiquer ca autour de moi